name: Sync to Public Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v3

      - name: Mirror to public repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git remote add public https://wathen:${{ secrets.PUBLIC_REPO_TOKEN1 }}@github.com/wathen/public_repo.git
          git push --force public main

